### PR TITLE
Feature/functionality recode

### PR DESCRIPTION
**Pull request by danyhoshi**
# Recode classes to functions

https://github.com/danyhoshi/todoList/assets/43626937/bfb0b9af-2f11-4e95-98f8-144881dab075

### CODE REVIEW

**Review by Edjhernandez — APPROVED** [review]
Hello estimed @danyhoshi !!! well done, this app works fine!
I just can suggest you add a cursor: pointer property for the 'clear all completed' button.

about the rest, you can merge!!!

**Comment by danyhoshi** [comment]
# The suggestion was applied 

# Thanks!!!

https://github.com/danyhoshi/todoList/assets/43626937/41f94773-d9e3-4b18-970b-db946aa29cc9

**Comment by Edjhernandez** [comment]
Great @danyhoshi , please merge it...

**Review by Edjhernandez — APPROVED** [review]
great job!!!!
please merge

**Pull request merged**
